

select *
from HR.EMPLOYEES
where DEPARTMENT_ID >= ALL (80,90,100);


SELECT *
FROM HR.EMPLOYEES
WHERE UPPER(LAST_NAME) = 'SMITH' AND SALARY > 7500;


SELECT *
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 10 OR DEPARTMENT_ID = 20;

SELECT *
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (10,20);


select *
from HR.EMPLOYEES
where SUBSTR(FIRST_NAME,1,1) BETWEEN 'A' and 'L'
order by 2;



-- OPERACIONES CON VALORES NULOS

SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT, 
SALARY * (1 + nvl(commission_pct,0)) TOTAL
FROM HR.EMPLOYEES;



-- NATURAL JOIN


SELECT COUNT(*) FROM HR.EMPLOYEES;

SELECT COUNT(*) FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL;

SELECT COUNT(*) FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IS NULL;


SELECT *
FROM HR.DEPARTMENTS NATURAL JOIN HR.EMPLOYEES;


SELECT * FROM HR.DEPARTMENTS;
SELECT * FROM HR.EMPLOYEES;


SELECT *
FROM HR.DEPARTMENTS JOIN HR.EMPLOYEES USING (DEPARTMENT_ID);


SELECT *
FROM HR.DEPARTMENTS D
JOIN HR.EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;



SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(1) EMPS
FROM HR.DEPARTMENTS D
JOIN HR.EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY 3 DESC;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(1) EMPS
FROM HR.DEPARTMENTS D
JOIN HR.EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(1) > 10
ORDER BY 3 DESC;









