-- -----------------------------------
-- TALLER DE BASE DE DATOS
-- EVALUACIÓN:   PRACTICA 01
-- FECHA:        23-NOV-2017
-- ESTUDIANTE 1: CRISTOPHER ALEXIS CASTILLO CASTILLO
-- ESTUDIANTE 2: SHIRLEY BENITTA CASTILLO YARLEQUE
-- -----------------------------------


-- -----------------------------------
-- ENVIO DE LA SOLUCION
-- -----------------------------------
-- CORREO: egcc.ucs@gmail.com
-- FECHA:  23-NOV-2017
-- HORA:   Hasta las 9:30 pm
-- ASUNTO: UCS TBD Practica 01
-- -----------------------------------


-- -----------------------------------
-- Pregunta 01
-- -----------------------------------
SELECT 'CURSO' AS "TIPO",CURSO.CUR_ID AS "CODIGO", CURSO.CUR_NOMBRE AS "NOMBRE" FROM CURSO , ALUMNO, MATRICULA
    WHERE CURSO.CUR_ID= MATRICULA.CUR_ID AND
      ALUMNO.ALU_ID = MATRICULA.ALU_ID
      GROUP BY CURSO.CUR_ID, CURSO.CUR_NOMBRE
      UNION ALL
SELECT 'ALUMNO' AS "TIPO", ALUMNO.ALU_ID AS "CODIGO", ALUMNO.ALU_NOMBRE AS "NOMBRE" FROM CURSO , ALUMNO, MATRICULA
    WHERE CURSO.CUR_ID= MATRICULA.CUR_ID AND
      ALUMNO.ALU_ID = MATRICULA.ALU_ID
      GROUP BY ALUMNO.ALU_ID,ALUMNO.ALU_NOMBRE;
      
 

-- -----------------------------------
-- Pregunta 02
-- -----------------------------------
SELECT CURSO.CUR_NOMBRE AS "NOMBRE DEL CURSO", 
       COUNT(MATRICULA.ALU_ID) AS "MATRICULADOS",
       SUM(MATRICULA.MAT_PRECIO) AS "IMPORTE COMPROMETIDO",
       SUM(PAGO.PAG_IMPORTE) AS "IMPORTE RECAUDADO",
       (SUM(MATRICULA.MAT_PRECIO)-SUM(PAGO.PAG_IMPORTE)) AS "IMPORTE PENDIENTE"
    FROM CURSO , ALUMNO, MATRICULA, PAGO
    WHERE CURSO.CUR_ID= MATRICULA.CUR_ID AND
      ALUMNO.ALU_ID = MATRICULA.ALU_ID AND 
      CURSO.CUR_ID= PAGO.CUR_ID AND
      ALUMNO.ALU_ID = PAGO.ALU_ID
GROUP BY CURSO.CUR_NOMBRE;

-- -----------------------------------
-- Pregunta 03
-- -----------------------------------
SELECT ALUMNO.ALU_NOMBRE AS "NOMBRE ALUMNO",
      CURSO.CUR_NOMBRE AS "NOMBRE CURSO", 
      MATRICULA.MAT_NOTA AS "NOTA"
    FROM CURSO , ALUMNO, MATRICULA
    WHERE CURSO.CUR_ID= MATRICULA.CUR_ID AND
      ALUMNO.ALU_ID = MATRICULA.ALU_ID AND MATRICULA.MAT_NOTA=(SELECT MAX(MATRICULA.MAT_NOTA) FROM MATRICULA)
    GROUP BY ALUMNO.ALU_NOMBRE,CURSO.CUR_NOMBRE, MATRICULA.MAT_NOTA;

-- -----------------------------------
-- Pregunta 04
-- -----------------------------------
SELECT LOCATIONS.CITY , COUNT(EMPLOYEES.EMPLOYEE_ID) FROM EMPLOYEES , DEPARTMENTS , LOCATIONS
    WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    AND   DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
GROUP BY LOCATIONS.CITY;


-- -----------------------------------
-- Pregunta 05
-- -----------------------------------
SELECT EMPLOYEES.JOB_ID, COUNT(EMPLOYEES.EMPLOYEE_ID) FROM EMPLOYEES 
    GROUP BY EMPLOYEES.JOB_ID
    HAVING COUNT(EMPLOYEES.EMPLOYEE_ID) > 2;

-- -----------------------------------
-- Pregunta 06
-- -----------------------------------
SELECT EMPLOYEES.DEPARTMENT_ID AS "DPTONRO", 
       EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME AS "EMPLEADO",
       (CASE
        WHEN EMPLOYEES.COMMISSION_PCT IS NULL THEN
            EMPLOYEES.SALARY
        WHEN EMPLOYEES.COMMISSION_PCT = 0 THEN
            EMPLOYEES.SALARY
         WHEN EMPLOYEES.COMMISSION_PCT IS NOT NULL THEN
            EMPLOYEES.SALARY
       END) AS "PLANILLA SIN COMISION",
       (CASE
        WHEN EMPLOYEES.COMMISSION_PCT IS NULL THEN
            EMPLOYEES.SALARY
        WHEN EMPLOYEES.COMMISSION_PCT = 0 THEN
            EMPLOYEES.SALARY
        WHEN EMPLOYEES.COMMISSION_PCT > 0 THEN
            (EMPLOYEES.SALARY*EMPLOYEES.COMMISSION_PCT)+EMPLOYEES.SALARY
       END) AS "PLANILLA CON COMISION"
       FROM EMPLOYEES , DEPARTMENTS 
    WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    GROUP BY EMPLOYEES.DEPARTMENT_ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME,EMPLOYEES.COMMISSION_PCT,EMPLOYEES.SALARY;
    


